### ISSUE TITLE
Cannot define azs

### ISSUE THREAD

**Issue by fmunteanu** [PowerDataHub/terraform-aws-airflow#19]
```
module "airflow_cluster" {
    source             = "powerdatahub/airflow/aws"
    version            = "0.8.11"
    ...
    ami                = "ami-005bdb005fb00e791" # us-west-2
    aws_region         = "us-west-2"
    azs = {
        "1"            = "us-west-2a",
        "2"            = "us-west-2b",
        "3"            = "us-west-2c"
    }
    ...
}
```
Error:
```
Error launching source instance: Unsupported: Your requested instance type (t3.micro) is not supported in your requested Availability Zone (us-west-2d). Please retry your request by not specifying an Availability Zone or choosing us-west-2a, us-west-2b, us-west-2c.
	status code: 400, request id: 7afc6751-570a-4bca-a1da-9a012b242919
```

**Comment by edbizarro** [comment]
Hi @fmunteanu, how many workers machines you have in your config ?

**Comment by fmunteanu** [comment]
@edbizarro all default settings, except the ususal changes to db_password, fernet_key, key_name and admin_*.

**Comment by fmunteanu** [comment]
Also there are no outputs printed, when I use the Terraform registry module, unless I missed a setting?

**Comment by fmunteanu** [comment]
I managed to deploy the cluster, after I cloned locally the v0.8.11 tag. However, the `webserver_admin_url` is not functional. Looking at the service into Ubuntu EC2 instance:
```
Jul 18 17:26:47 ip-172-31-40-22 systemd[1]: Started Airflow daemon.
Jul 18 17:26:47 ip-172-31-40-22 terraform-aws-airflow[25465]: [2019-07-18 17:26:47,651] {settings.py:182} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=25465
Jul 18 17:26:47 ip-172-31-40-22 terraform-aws-airflow[25465]: [2019-07-18 17:26:47,879] {__init__.py:51} INFO - Using executor CeleryExecutor
Jul 18 17:26:48 ip-172-31-40-22 terraform-aws-airflow[25465]:   ____________       _____________
Jul 18 17:26:48 ip-172-31-40-22 terraform-aws-airflow[25465]:  ____    |__( )_________  __/__  /________      __
Jul 18 17:26:48 ip-172-31-40-22 terraform-aws-airflow[25465]: ____  /| |_  /__  ___/_  /_ __  /_  __ \_ | /| / /
Jul 18 17:26:48 ip-172-31-40-22 terraform-aws-airflow[25465]: ___  ___ |  / _  /   _  __/ _  / / /_/ /_ |/ |/ /
Jul 18 17:26:48 ip-172-31-40-22 terraform-aws-airflow[25465]:  _/_/  |_/_/  /_/    /_/    /_/  \____/____/|__/
Jul 18 17:26:48 ip-172-31-40-22 terraform-aws-airflow[25465]: [2019-07-18 17:26:48,581] {__init__.py:305} INFO - Filling up the DagBag from /dev/null
Jul 18 17:26:49 ip-172-31-40-22 terraform-aws-airflow[25465]: [2019-07-18 17:26:49,148] {security.py:446} INFO - Start syncing user roles.
Jul 18 17:26:49 ip-172-31-40-22 terraform-aws-airflow[25465]: [2019-07-18 17:26:49,624] {security.py:357} INFO - Fetching a set of all permission, view_menu from FAB meta-table
Jul 18 17:26:49 ip-172-31-40-22 terraform-aws-airflow[25465]: [2019-07-18 17:26:49,963] {security.py:307} INFO - Cleaning faulty perms
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]: [2019-07-18 17:26:50,633] {settings.py:182} INFO - settings.configure_orm(): Using pool settings. pool_size=5, pool_recycle=1800, pid=25507
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]: /usr/local/lib/python3.6/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:   """)
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]: [2019-07-18 17:26:50 +0000] [25507] [INFO] Starting gunicorn 19.9.0
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]: Traceback (most recent call last):
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:   File "/usr/local/bin/gunicorn", line 11, in <module>
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:     sys.exit(run())
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 61, in run
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 223, in run
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:     super(Application, self).run()
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:   File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 72, in run
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:     Arbiter(self).run()
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 199, in run
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:     self.start()
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:   File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 139, in start
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:     self.pidfile.create(self.pid)
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:   File "/usr/local/lib/python3.6/dist-packages/gunicorn/pidfile.py", line 36, in create
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:     fd, fname = tempfile.mkstemp(dir=fdir)
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:   File "/usr/lib/python3.6/tempfile.py", line 483, in mkstemp
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:     return _mkstemp_inner(dir, prefix, suffix, flags, output_type)
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:   File "/usr/lib/python3.6/tempfile.py", line 401, in _mkstemp_inner
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]:     fd = _os.open(file, flags, 0o600)
Jul 18 17:26:50 ip-172-31-40-22 terraform-aws-airflow[25465]: PermissionError: [Errno 13] Permission denied: '/usr/local/airflow/tmpqk3e9n1v'
```
